import org.apache.hadoop.security.proto.RefreshUserMappingsProtocolProtos.RefreshUserToGroupsMappingsResponseProto;
public class FunctionUse13677 {
public void funcUse() {
RefreshUserToGroupsMappingsResponseProto refreshusertogroupsmappingsresponseproto = new RefreshUserToGroupsMappingsResponseProto();
refreshusertogroupsmappingsresponseproto.internalGetFieldAccessorTable();
}
}